apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: codegen-070312
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codegen-070312
  name: codegen-070312
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
